spring:
  application:
    name: eem

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:eem_ali}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


app:
  jwt:
    secret: U2FsdGVkX19osuGIYdp95E1jk3P+U++wyKTxHLUQ4c0= # AES256
    access-token-expiration-ms: 900000  # 15 minutes
    refresh-token-expiration-ms: 604800000  # 7 days
    issuer: study4ever-auth-service